# STLab02 – EduCommerce: CSV Data-driven Test Execution

In [1]:
from pathlib import Path
import sys
print('Python:', sys.version.split()[0])
print('Colab working directory:', Path.cwd())

Python: 3.13.16
Colab working directory: /content

## 1. Upload source và CSV

In [2]:
from google.colab import files
uploaded = files.upload()
for name in ('ecommerce_app.py', 'test_runner.py', 'test_cases.csv'):
    if not Path(name).exists():
        raise FileNotFoundError(f'Chưa có file bắt buộc: {name}')
print('READY: source and CSV present')

Saving ecommerce_app.py to ecommerce_app.py
Saving test_cases.csv to test_cases.csv
Saving test_runner.py to test_runner.py
READY: source and CSV present

## 2. Chạy 33 test cases

In [3]:
import subprocess
command = [sys.executable, 'test_runner.py', '--cases', 'test_cases.csv', '--out', 'reports']
completed = subprocess.run(command, text=True, capture_output=True)
print(completed.stdout)
if completed.stderr:
    print('STDERR:', completed.stderr)
print('Runner exit code:', completed.returncode)

Thời điểm chạy (UTC): 2026-10-27T16:27:02+00:00
TC-CART-001          REQ-02  PASS
TC-CART-002          REQ-02  PASS
TC-CART-003          REQ-02  PASS
TC-CART-004          REQ-02  PASS
TC-CART-005          REQ-02  PASS
TC-CART-006          REQ-02  PASS
TC-CART-007          REQ-02  PASS
TC-PROMO7-001        REQ-07  PASS
TC-PROMO7-002        REQ-07  PASS
TC-PROMO7-003        REQ-07  PASS
TC-PROMO7-004        REQ-07  PASS
TC-PROMO7-005        REQ-07  PASS
TC-PROMO7-006        REQ-07  PASS
TC-PROMO7-007        REQ-07  PASS
TC-SHIP-001          REQ-09  PASS
TC-SHIP-002          REQ-09  PASS
TC-SHIP-003          REQ-09  PASS
TC-SHIP-004          REQ-09  PASS
TC-SHIP-005          REQ-09  PASS
TC-SHIP-006          REQ-09  PASS
TC-PAY-001           REQ-10  PASS
TC-PAY-002           REQ-10  PASS
TC-PAY-003           REQ-10  PASS
TC-PAY-004           REQ-10  PASS
TC-PAY-005           REQ-10  PASS
TC-PAY-006           REQ-10  PASS
TC-INV15-001         REQ-15  PASS
TC-INV15-002         REQ-15  PASS
TC-INV15-003         REQ-15  PASS
TC-INV15-004         REQ-15  PASS
TC-INV15-005         REQ-15  PASS
TC-INV15-006         REQ-15  PASS
TC-INV15-007         REQ-15  PASS
TOTAL=33 PASS=33 FAIL=0 BLOCKED=0 PASS_RATE_EXECUTED=100.0%
Các tệp kết quả: reports/run_metadata.json, reports/test_dashboard.html, reports/test_execution.csv, reports/test_summary.csv, reports/traceability_execution.csv

Runner exit code: 0

## 3. Xem report và kiểm tra số case đã nạp

In [4]:
import pandas as pd
from IPython.display import display
summary = pd.read_csv('reports/test_summary.csv')
execution = pd.read_csv('reports/test_execution.csv', keep_default_na=False)
display(summary)
display(execution[['test_case_id','requirement_id','execution_status','execution_time_ms','error_message']])
print('Loaded:', len(execution), ' / PASS+FAIL+BLOCKED:', execution['execution_status'].isin(['PASS','FAIL','BLOCKED']).sum())

  requirement_id  loaded  PASS  FAIL  BLOCKED
0         REQ-02       7     7     0        0
1         REQ-07       7     7     0        0
2         REQ-09       6     6     0        0
3         REQ-10       6     6     0        0
4         REQ-15       7     7     0        0

,test_case_id,requirement_id,execution_status,execution_time_ms,error_message
0,TC-CART-001,REQ-02,PASS,0.163,
1,TC-CART-002,REQ-02,PASS,0.092,
2,TC-CART-003,REQ-02,PASS,0.094,
3,TC-CART-004,REQ-02,PASS,0.063,
4,TC-CART-005,REQ-02,PASS,0.055,
5,TC-CART-006,REQ-02,PASS,0.042,
6,TC-CART-007,REQ-02,PASS,0.036,
7,TC-PROMO7-001,REQ-07,PASS,0.055,
8,TC-PROMO7-002,REQ-07,PASS,0.055,
9,TC-PROMO7-003,REQ-07,PASS,0.099,
10,TC-PROMO7-004,REQ-07,PASS,0.098,
11,TC-PROMO7-005,REQ-07,PASS,0.080,
12,TC-PROMO7-006,REQ-07,PASS,0.048,
13,TC-PROMO7-007,REQ-07,PASS,0.064,
14,TC-SHIP-001,REQ-09,PASS,0.037,
15,TC-SHIP-002,REQ-09,PASS,0.032,
16,TC-SHIP-003,REQ-09,PASS,0.029,
17,TC-SHIP-004,REQ-09,PASS,0.031,
18,TC-SHIP-005,REQ-09,PASS,0.027,
19,TC-SHIP-006,REQ-09,PASS,0.029,
20,TC-PAY-001,REQ-10,PASS,0.060,
21,TC-PAY-002,REQ-10,PASS,0.053,
22,TC-PAY-003,REQ-10,PASS,0.071,
23,TC-PAY-004,REQ-10,PASS,0.057,
24,TC-PAY-005,REQ-10,PASS,0.056,
25,TC-PAY-006,REQ-10,PASS,0.049,
26,TC-INV15-001,REQ-15,PASS,0.073,
27,TC-INV15-002,REQ-15,PASS,0.064,
28,TC-INV15-003,REQ-15,PASS,0.062,
29,TC-INV15-004,REQ-15,PASS,0.064,
30,TC-INV15-005,REQ-15,PASS,0.056,
31,TC-INV15-006,REQ-15,PASS,0.063,
32,TC-INV15-007,REQ-15,PASS,0.061,

Loaded: 33  / PASS+FAIL+BLOCKED: 33

## 4. Mở dashboard HTML tại Colab

In [5]:
from IPython.display import HTML, display
display(HTML(Path('reports/test_dashboard.html').read_text(encoding='utf-8')))

## 5. Tải kết quả về Windows

In [6]:
import shutil
from google.colab import files
archive = shutil.make_archive('STLab02_Colab_Execution', 'zip', 'reports')
files.download(archive)